export const statesAbvs: { [key: string]: string } = {
  all: 'Todos',
  agu: 'Aguascalientes',
  bcn: 'Baja California',
  bcs: 'Baja California Sur',
  cam: 'Campeche',
  chp: 'Chiapas',
  chh: 'Chihuahua',
  cmx: 'Ciudad de Mexico',
  coa: 'Coahuila',
  col: 'Colima',
  dur: 'Durango',
  gua: 'Guanajuato',
  gro: 'Guerrero',
  hid: 'Hidalgo',
  jal: 'Jalisco',
  mex: 'Estado de Mexico',
  mic: 'Michoacan',
  mor: 'Morelos',
  nay: 'Nayarit',
  nle: 'Nuevo Leon',
  oax: 'Oaxaca',
  pue: 'Puebla',
  que: 'Queretaro',
  roo: 'Quintana Roo',
  slp: 'San Luis Potosi',
  sin: 'Sinaloa',
  son: 'Sonora',
  tab: 'Tabasco',
  tam: 'Tamaulipas',
  tla: 'Tlaxcala',
  ver: 'Veracruz',
  yuc: 'Yucatan',
  zac: 'Zacatecas',
};
